name: avpos
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pytorch>=2.1
  - torchvision>=0.16
  - numpy>=1.24
  - pandas>=2.0
  - matplotlib>=3.7
  - seaborn>=0.12
  - scikit-learn>=1.3
  - pillow>=10.0
  - opencv>=4.8
  - tqdm>=4.65
  - pip
  - pip:
    - facenet-pytorch>=2.5
    - mlflow>=2.5
    - kornia>=0.7
    - wandb>=0.15
    - tensorboard>=2.13
